services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend/dist:/app/dist
    networks:
      - app-network


  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=demo
    command: --bind-address=0.0.0.0  # 允许所有IP连接
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/demo.sql:/docker-entrypoint-initdb.d/init.sql  # 挂载初始化SQL
    ports:
      - "3306:3306"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # 挂载自定义配置
      - ./frontend/dist:/usr/share/nginx/html  # 挂载前端静态文件（替代前端服务）
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge

